# Generated by Django 6.0.6 on 2026-08-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('Médicaments', 'Médicaments'), ('Dispositifs', 'Dispositifs'), ('Solutés', 'Solutés')], max_length=30)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('min_stock', models.PositiveIntegerField(default=10)),
                ('max_stock', models.PositiveIntegerField(default=100)),
                ('expiration', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('packaging', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
